### ISSUE TITLE
Issue when trying to run app (build succeeds). All components updated to newest version

### ISSUE THREAD

**Issue by dodokov** [googlesamples/android-XYZTouristAttractions#3]
04-29 08:13:46.757  25190-25232/com.example.android.xyztouristattractions E/AndroidRuntime﹕ FATAL EXCEPTION: IntentService[UtilityService]
    Process: com.example.android.xyztouristattractions, PID: 25190
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$c;
            at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
            at com.example.android.xyztouristattractions.service.UtilityService.addGeofencesInternal(UtilityService.java:153)
            at com.example.android.xyztouristattractions.service.UtilityService.onHandleIntent(UtilityService.java:125)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$c" on path: DexPathList[[zip file "/data/app/com.example.android.xyztouristattractions-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
            at com.example.android.xyztouristattractions.service.UtilityService.addGeofencesInternal(UtilityService.java:153)
            at com.example.android.xyztouristattractions.service.UtilityService.onHandleIntent(UtilityService.java:125)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Api$c
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 8 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by dhaval0122** [comment]
make sure you have used latest Google play service

**Comment by dodokov** [comment]
Yes, manually chaning build.gradle to : compile "com.google.android.gms:play-services-location:7.3.0" got it to work... thx

**Comment by adamkoch** [comment]
Sorry about that, latest auto-push from our servers put inconsistent versions in the build.gradle files for play services. I'll get it fixed and pushed out again.

**Comment by carloshwa** [comment]
The build.gradle files are a mess. I also had to add:
`compile "com.google.android.gms:play-services-identity:7.3.0"`
to the Application build.gradle to get it to run.

**Comment by Ogamedia** [comment]
Adding  "com.google.android.gms:play-services-location:7.3.0" just like @dodokov worked for me as well.
Thanks @dodokov

**Comment by adamkoch** [comment]
Fixed in latest push.
