### ISSUE TITLE
Notification Error

### ISSUE THREAD

**Issue by tomlear** [googlesamples/android-XYZTouristAttractions#6]
Hi, 

I do not get a notification when i visit the certain area, I've even used FakeGPS to make sure its exactly the same longitude and latitude. Also when i tap on "Test Notification" the app crashes and says "Unfortunately xxxxxxx has stopped working"

Please can you help me ASAP

**Comment by adamkoch** [comment]
Can you post the stack trace as well as device setup (which devices, OS versions etc).

**Comment by tomlear** [comment]
How do I do that? I'm not 100% sure.

Thanks

**Comment by adamkoch** [comment]
Use adb [logcat](https://developer.android.com/studio/command-line/logcat.html) or run "adb bugreport" to capture the logs when the error happens.

**Comment by tomlear** [comment]
Hi heres the logcat: 

07-22 19:45:55.905 3405-3405/com.example.android.xyztouristattractions D/Atlas: Validating map...
07-22 19:45:55.909 3405-3429/com.example.android.xyztouristattractions V/UtilityService: add_geofences
07-22 19:45:55.959 3405-3426/com.example.android.xyztouristattractions I/OpenGLRenderer: Initialized EGL, version 1.4
07-22 19:45:55.977 3405-3426/com.example.android.xyztouristattractions D/OpenGLRenderer: Enabling debug mode 0
07-22 19:45:55.997 3405-3426/com.example.android.xyztouristattractions W/EGL_emulation: eglSurfaceAttrib not implemented
07-22 19:45:55.998 3405-3426/com.example.android.xyztouristattractions W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fcb9800ce40, error=EGL_SUCCESS
07-22 19:45:56.652 3405-3429/com.example.android.xyztouristattractions V/UtilityService: request_location
07-22 19:45:56.955 3405-3429/com.example.android.xyztouristattractions V/UtilityService: request_location
07-22 19:45:58.270 3405-3405/com.example.android.xyztouristattractions I/Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
07-22 20:01:01.111 3405-3405/com.example.android.xyztouristattractions W/art: Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
07-22 20:01:01.140 3405-3413/com.example.android.xyztouristattractions W/art: Suspending all threads took: 16.778ms
07-22 20:01:01.188 3405-3426/com.example.android.xyztouristattractions W/EGL_emulation: eglSurfaceAttrib not implemented
07-22 20:01:01.188 3405-3426/com.example.android.xyztouristattractions W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fcb95189540, error=EGL_SUCCESS
07-22 20:01:02.480 3405-3405/com.example.android.xyztouristattractions I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
07-22 20:01:02.545 3405-3426/com.example.android.xyztouristattractions W/EGL_emulation: eglSurfaceAttrib not implemented
07-22 20:01:02.545 3405-3426/com.example.android.xyztouristattractions W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fcb95189500, error=EGL_SUCCESS

```
   --------- beginning of crash
```

07-22 20:01:02.800 3405-16788/com.example.android.xyztouristattractions E/AndroidRuntime: FATAL EXCEPTION: IntentService[UtilityService]
                                                                                          Process: com.example.android.xyztouristattractions, PID: 3405
                                                                                          java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
                                                                                              at com.example.android.xyztouristattractions.service.UtilityService.showNotification(UtilityService.java:371)
                                                                                              at com.example.android.xyztouristattractions.service.UtilityService.onHandleIntent(UtilityService.java:143)
                                                                                              at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 20:01:03.670 3405-3405/com.example.android.xyztouristattractions E/WindowManager: android.view.WindowLeaked: Activity com.example.android.xyztouristattractions.ui.AttractionListActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{17de67d1 V.E..... R....... 0,0-1080,998} that was originally added here
                                                                                            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
                                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                                            at android.app.Dialog.show(Dialog.java:298)
                                                                                            at com.example.android.xyztouristattractions.ui.AttractionListActivity.showDebugDialog(AttractionListActivity.java:168)
                                                                                            at com.example.android.xyztouristattractions.ui.AttractionListActivity.onOptionsItemSelected(AttractionListActivity.java:95)
                                                                                            at android.app.Activity.onMenuItemSelected(Activity.java:2885)
                                                                                            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:404)
                                                                                            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
                                                                                            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                                                            at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:583)
                                                                                            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
                                                                                            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
                                                                                            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                                                            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
                                                                                            at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
                                                                                            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                                                            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
                                                                                            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
                                                                                            at android.widget.AbsListView$3.run(AbsListView.java:3860)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-22 20:01:05.297 3405-16788/com.example.android.xyztouristattractions I/Process: Sending signal. PID: 3405 SIG: 9

This was on an emulator w/ Nexus 5 API 22 Android 5.1.1

But I also get the same error on my HTC one m7 which has: 5.0.2 API 21

**Comment by tomlear** [comment]
Hi Adam,

Did you manage to have a look at this??

**Comment by adamkoch** [comment]
Can you try switching the getColor() call to ContextCompat.getColor() as per:
http://stackoverflow.com/a/33203166/268156

**Comment by tomlear** [comment]
I've added "compile 'com.android.support:support-v4:23.0.1'" to the dependencies array inside build.gradle. But where do I change "getColor() call to ContextCompat.getColor()".

Cheers

**Comment by adamkoch** [comment]
Don't your gradle files, just use it as it is from the repo. The method to change as per your crash report is:
https://github.com/googlesamples/android-XYZTouristAttractions/blob/master/Application/src/main/java/com/example/android/xyztouristattractions/service/UtilityService.java#L371

**Comment by tomlear** [comment]
So it should be: 

.setColor(getResources()ContextCompat.getColor(R.color.colorPrimary, getTheme()))

Instead of: 

.setColor(getResources().getColor(R.color.colorPrimary, getTheme()))

Thanks.

**Comment by adamkoch** [comment]
You should try:
.setColor(ContextCompat.getColor(R.color.colorPrimary, getTheme()))

**Comment by tomlear** [comment]
Getting this error when i try and run the app:

Error:(372, 57) error: incompatible types: int cannot be converted to Context
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Error:Execution failed for task ':Application:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

**Comment by adamkoch** [comment]
Sorry the params are actually context and color resource:
https://developer.android.com/reference/android/support/v4/content/ContextCompat.html#getColor(android.content.Context, int)

**Comment by tomlear** [comment]
So what should i put instead of:

 .setColor(ContextCompat.getColor(R.color.colorPrimary, getTheme()))

**Comment by tomlear** [comment]
????

**Comment by adamkoch** [comment]
The docs say to pass a context and a resource ID. Did you try that?

If you are having general problems understanding Android development I would recommend stackoverflow.com as the best place for questions and answers. This is not really the right forum for that.
